application: himepostoffice
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /_ah/channel/connected/
  script: main.app

- url: /_ah/channel/disconnected/
  script: main.app
  
- url: /
  script: main.app

- url: /.*
  script: main.app
  login: required
  
libraries:
- name: webapp2
  version: latest
  
- name: jinja2
  version: latest

pagespeed:
  enabled_rewriters:
  - MinifyCss

inbound_services:
- channel_presence
